spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/your-db
    username: your username
    password: your password
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: your username
    password: your password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true
time:
  jwt: 5
  refresh: 5
  signup: 5
openapi:
  dev-url: development url
  prod-url: production url
google-api-key: your-key
task:
  purge: schedule in cron