# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123654
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  application:
    name: app
# Server configuration
server:
  port: 8090
jwt:
  expiration:
    time: 9000000000000000
signup:
  token:
    time: 9000000000000000
sport:
  maps:
    openapi:
      dev-url: http://localhost:8090

      prod-url: http://localhost:8090
google-api-key: AIzaSyCqKqPQNYTDZ-6YLP8UQwCeKBrBOWPLg6M